name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x, 20.x, 21.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      #TODO: Migrate to GitHub CI App
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.TEMP_DEPLOY_KEY }}
            ${{ secrets.TEMP_SC_DEPLOY_KEY }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install Astro
        run: npm install -g astro
      - name: Install Dependencies
        run: npm install
      - name: Run Build
        run: npm run build --if-present
      - name: Lint Codebase
        run: npm run lint --if-present
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build Storybook
        run: npm run build-storybook --quiet
      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006" \
            "npx wait-on http://127.0.0.1:6006 && npm run coverage"
#      TODO: Publish Coverage Reports
#      - name: Publish code coverage
#        if: matrix.node-version == '22.x'
#        uses: paambaati/codeclimate-action@v8.0.0
#        env:
#          CC_TEST_REPORTER_ID: ${{secrets.CODE_CLIMATE_REPORTER_ID}}
#        with:
#          coverageCommand: npm run coverage
